### ISSUE TITLE
Sending variable data from one for to another

### ISSUE THREAD

**Issue by doctormari** [addanny/WilliamsGit#1]
That's the biggest issue I am having at the moment. I am unable to send the variables from the products page to the shop page. Will be working on that further.

**Comment by doctormari** [comment]
Change the product class to a static class. Will attempt this later
//this is more a reminder

**Comment by JAMORALES** [comment]
I found this:

C#

String s = Request.QueryString["field1"];

VB

Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) _
        Handles Me.Load
    Dim displayValues As New StringBuilder()
    Dim postedValues As NameValueCollection = Request.Form
    Dim nextKey As String
    For i As Integer = 0 To postedValues.AllKeys.Length - 1
        nextKey = postedValues.AllKeys(i)
        If nextKey.Substring(0, 2) <> "__" Then
            displayValues.Append("<br>")
            displayValues.Append(nextKey)
            displayValues.Append(" = ")
            displayValues.Append(postedValues(i))
        End If
    Next
    Label1.Text = displayValues.ToString()
 End Sub

https://msdn.microsoft.com/en-us/library/6c3yckfw%28v=vs.140%29.aspx?cs-save-lang=1&cs-lang=vb#code-snippet-2

**Comment by doctormari** [comment]
thanks - working today so ill play with it tonight

**Comment by doctormari** [comment]
changed it to a messagebox instead. Works.
